/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.loan_officer;
import Controller.loan;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Date;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;
import Model.connect;

/**
 *
 * @author Ahmed Elkersh
 */
public class LoanFrame extends javax.swing.JFrame {

    Vector<Double> lo_money = new Vector<Double>();
    Vector<Double> up_money = new Vector<Double>();
    connect c = new connect();
    

    /**
     * Creates new form NewJFrame
     */
    public LoanFrame() {
        initComponents();
        loan g = new loan();
        g.setGuarantee("- You can take loan for up to 7 years\n- Client age range is between 21 and 60 years\n"
                + "- The minimum monthly salary is 1000 LE\n- The minimum value of the loan is five thousand Egyptian pounds and a maximum of 500 thousand Egyptian pounds\n"
                + "- A guarantor is not required");
        jTextArea1.setText(g.getGuarantee());
        jTextArea1.setEditable(false);
        btn_submit.setEnabled(false);
        update_table();
        //update_date();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        yes = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txt_nid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_money = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_years = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        yes.setText("client agree");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("National ID");

        txt_nid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nidActionPerformed(evt);
            }
        });
        txt_nid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nidKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Money");

        txt_money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_moneyActionPerformed(evt);
            }
        });
        txt_money.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_moneyKeyTyped(evt);
            }
        });

        btn_submit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Years");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Name");

        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nameKeyTyped(evt);
            }
        });

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jButton2.setText("View archive");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setText("inquire ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setText("clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(yes))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(135, 135, 135)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_money, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                        .addComponent(txt_nid)
                                        .addComponent(txt_years)
                                        .addComponent(txt_name))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btn_submit)
                                .addGap(43, 43, 43)
                                .addComponent(btn_update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(jButton2)
                                .addGap(210, 210, 210))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(yes)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_nid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_years, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_update)
                            .addComponent(btn_submit)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jButton2)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed

        if (yes.isSelected()) {
            btn_submit.setEnabled(true);
        } else {
            btn_submit.setEnabled(false);
        }
    }//GEN-LAST:event_yesActionPerformed
    private void update_table() {
        try {
            ResultSet result = connect.startConnectionStatement().executeQuery("select * from loan");
            jTable1.setModel(DbUtils.resultSetToTableModel(result));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally{
            connect.closeConnection();
        }
    }

    private int check(String nnid) {
        int months = 0;
        try {
            ResultSet r = connect.startConnectionStatement().executeQuery("select loan_date,today_date from loan where  loan_NID = '" + nnid + "'");
            Date l_Date = new Date(0);
            Date t_date = new Date(0);
            while (r.next()) {
                l_Date = r.getDate(1);
                t_date = r.getDate(2);
            }
            System.out.println(l_Date + "          " + t_date);

            long diff = t_date.getTime() - l_Date.getTime();
            int days = (int) (TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS));
            months = (int) (days / 30) + 1;
            System.out.println("days : " + days);

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally{
            connect.closeConnection();
        }
        return months;
    }

    public void clear() {
        txt_nid.setText("");
        txt_name.setText("");
        txt_money.setText("");
        txt_years.setText("");
    }

    private void update_date() {
        try {
            java.sql.Timestamp date = new java.sql.Timestamp(new java.util.Date().getTime());

            String sql = " update loan set today_date = '" + date + "' ";
            PreparedStatement pst = (PreparedStatement) connect.startConnection().prepareStatement(sql);
            pst.execute();
            update_table();
        } catch (Exception ex) {

        } finally{
            connect.closeConnection();
        }

    }
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        int t = Integer.parseInt(txt_money.getText());
        int y = Integer.parseInt(txt_years.getText());
        if (txt_nid.getText().equals("") || txt_money.getText().equals("") || txt_years.getText().equals("") || txt_name.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill all Fields To Save");
        } else if (txt_nid.getText().length() != 14) {
            JOptionPane.showMessageDialog(null, "Please Enter Right Nationa id");
        } else if (t < 5000 || t > 500000) {
            JOptionPane.showMessageDialog(null, "Please put money bigger than or equal 5000");
        } else if (y < 1 || y > 7) {
            JOptionPane.showMessageDialog(null, "Please year can't be more than 7 years");
        } else {
            try {
                loan_officer o = new loan_officer();
                Double mon = Double.parseDouble(txt_money.getText());
                o.manage_loan(txt_nid.getText(), mon);

                update_table();
                clear();
                JOptionPane.showMessageDialog(null, "Saved");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            } finally{
            connect.closeConnection();
        }
        }

    }//GEN-LAST:event_btn_submitActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            int row = jTable1.getSelectedRow();
            txt_nid.setEditable(false);
            txt_years.setEditable(false);
            txt_name.setEditable(false);

            // get data from cloumn 1
            String id = (jTable1.getModel().getValueAt(row, 0).toString());

            ResultSet result = connect.startConnectionStatement().executeQuery("select * from loan where loan_NID = '" + id + "'");

            if (result.next()) {
                String add1 = result.getString("loan_NID");
                txt_nid.setText(add1);
                String add4 = result.getString("loan_name");
                txt_name.setText(add4);
                String add3 = result.getString("loan_year");
                txt_years.setText(add3);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally{
            connect.closeConnection();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        up_money.clear();
        if (txt_nid.getText().equals("") || txt_money.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill all Fields To Save");
        } else {
            try {
                String name = txt_name.getText();
                String nid = txt_nid.getText();
                Double money = Double.parseDouble(txt_money.getText());

                int mon = check(nid);
                ResultSet r = connect.startConnectionStatement().executeQuery("select * from loan where loan_NID= '" + txt_nid.getText() + "'");
                Double l_money = 0.0;
                Double now_money = 0.0;
                int flag = 0;
                int year = Integer.parseInt(txt_years.getText());
                while (r.next()) {
                    now_money = r.getDouble(3);
                    l_money = r.getDouble(9);
                    flag = r.getInt(8);
                }

                for (int i = year; i >= 1; i--) {
                    //our loan law
                    up_money.add(((((l_money * i * 7) / (year * 100)) + (l_money / year)) / 12));
                }
                long x = 0;
                if (mon <= 12) {
                    x = Math.round(up_money.get(0));
                } else if (mon <= 24) {
                    x = Math.round(up_money.get(1));
                } else if (mon <= 36) {
                    x = Math.round(up_money.get(2));
                } else if (mon <= 48) {
                    x = Math.round(up_money.get(3));
                } else if (mon <= 60) {
                    x = Math.round(up_money.get(4));
                } else if (mon <= 72) {
                    x = Math.round(up_money.get(5));
                } else if (mon <= 84) {
                    x = Math.round(up_money.get(6));
                }
                if (mon <= flag) {
                    JOptionPane.showMessageDialog(null, "you have paied what you must pay until now");
                } else {
                    if (money == x) {
                        flag += 1;
                        Double mm = now_money - money;
                        String sql = " update loan set loan_money = " + mm + " , loan_flag =" + flag + "  where loan_NID = '" + nid + "' ";
                        PreparedStatement pst = (PreparedStatement) connect.startConnection().prepareStatement(sql);
                        pst.execute();
                        update_table();
                    } else if (money > x) {
                        flag += 1;
                        Double mmm = now_money - x;
                        String sql = " update loan set loan_money = " + mmm + " , loan_flag =" + flag + "  where loan_NID = '" + nid + "' ";
                        PreparedStatement pst = (PreparedStatement) connect.startConnection().prepareStatement(sql);
                        pst.execute();
                        update_table();
                        Double rest = money - x;
                        JOptionPane.showMessageDialog(null, "here is the rest " + rest + " ");
                    } else {
                        JOptionPane.showMessageDialog(null, "you entered money under what you must pay if you don't know check how much money do you must pay ");
                    }

                    ResultSet rr = connect.startConnectionStatement().executeQuery("select * from loan where loan_NID= '" + nid + "'");
                    double monn = 0.0;
                    double total = 0.0;
                    while (rr.next()) {
                        monn = rr.getDouble("loan_money");
                        total = rr.getDouble("total_money");
                    }
                    if (monn == 0.0) {
                        //delete and insert into arshif
                        connect.startConnectionStatement().executeUpdate("insert into arshif (arshif_NID,arshif_name,arshif_money,arshif_year) values ('" + nid + "','" + name + "'," + total + "," + year + ")");
                        connect.startConnectionStatement().executeUpdate("delete from loan where loan_NID= '" + nid + "' ");
                        update_table();
                    }
                    txt_nid.setEditable(true);
                    txt_years.setEditable(true);
                    txt_name.setEditable(true);
                    clear();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            } finally{
            connect.closeConnection();
        }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_moneyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_moneyKeyTyped
        char c = evt.getKeyChar();
        if (Character.isAlphabetic(c)) {
            evt.consume();
        } else if (!Character.isDigit(evt.getKeyChar()) & txt_money.getText().indexOf(".") != -1) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_moneyKeyTyped

    private void txt_nidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nidKeyTyped
        String s = txt_nid.getText();
        if (s.length() == 14) {
            evt.consume();
        } else {
            char c = evt.getKeyChar();
            if (!Character.isDigit(c)) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_nidKeyTyped

    private void txt_moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_moneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_moneyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new LoginFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_nidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nidActionPerformed

    }//GEN-LAST:event_txt_nidActionPerformed

    private void txt_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isAlphabetic(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nameKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new archive().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            lo_money.clear();
            int month = check(txt_nid.getText());
            ResultSet rr = connect.startConnectionStatement().executeQuery("select * from loan where loan_NID= '" + txt_nid.getText() + "'");
            Double l_money = 0.0;
            int flag = 0;
            int year = Integer.parseInt(txt_years.getText());
            while (rr.next()) {
                l_money = rr.getDouble(9);
                flag = rr.getInt(8);
            }

            for (int i = year; i >= 1; i--) {
                //our loan law
                lo_money.add(((((l_money * i * 7) / (year * 100)) + (l_money / year)) / 12));
            }
            String msg = "";
            if (month <= 12) {
                msg += "you have paied " + flag + " Months\n";
                if (month == flag) {
                    msg += "your loan is at " + month + " Month and you have paied this month  \n                                      thanks";
                    JOptionPane.showMessageDialog(null, msg);
                } else {
                    int rest = month - flag;
                    msg += "your loan is at " + month + " Month and you will have to pay " + (rest * lo_money.get(0)) +" but for this month "+lo_money.get(0)+ "\n                                     thanks";
                    JOptionPane.showMessageDialog(null, msg);
                }
            } else if (month <= 24) {
                msg += "you have paied " + flag + " Months\n";
                if (month == flag) {
                    msg += "your loan is at " + month + " Month and you have paied this month  \n                                      thanks";
                    JOptionPane.showMessageDialog(null, msg);
                } else {
                    int rest = month - flag;            
                    msg += "your loan is at " + month + " Month and you will have to pay " + (rest * lo_money.get(1)) + " but for this month "+lo_money.get(1)+"\n                                     thanks";
                    JOptionPane.showMessageDialog(null, msg);
                }
            } else if (month <= 36) {
                msg += "you have paied " + flag + " Months\n";
                if (month == flag) {
                    msg += "your loan is at " + month + " Month and you have paied this month  \n                            thanks";
                    JOptionPane.showMessageDialog(null, msg);
                } else {
                    int rest = month - flag;
                    msg += "your loan is at " + month + " Month and you will have to pay " + (rest * lo_money.get(2)) + " but for this month "+lo_money.get(2)+"\n                                     thanks";
                    JOptionPane.showMessageDialog(null, msg);
                }
            } else if (month <= 48) {
                msg += "you have paied " + flag + " Months\n";
                if (month == flag) {
                    msg += "your loan is at " + month + " Month and you have paied this month  \n                            thanks";
                    JOptionPane.showMessageDialog(null, msg);
                } else {
                    int rest = month - flag;
                    msg += "your loan is at " + month + " Month and you will have to pay " + (rest * lo_money.get(3)) +  " but for this month "+lo_money.get(3)+"\n                                        thanks";
                    JOptionPane.showMessageDialog(null, msg);
                }
            } else if (month <= 60) {
                msg += "you have paied " + flag + " Months\n";
                if (month == flag) {
                    msg += "your loan is at " + month + " Month and you have paied this month  \n                            thanks";
                    JOptionPane.showMessageDialog(null, msg);
                } else {
                    int rest = month - flag;
                    msg += "your loan is at " + month + " Month and you will have to pay " + (rest * lo_money.get(4)) +  " but for this month "+lo_money.get(4)+"\n                                         thanks";
                    JOptionPane.showMessageDialog(null, msg);
                }
            } else if (month <= 72) {
                msg += "you have paied " + flag + " Months\n";
                if (month == flag) {
                    msg += "your loan is at " + month + " Month and you have paied this month  \n                            thanks";
                    JOptionPane.showMessageDialog(null, msg);
                } else {
                    int rest = month - flag;
                    msg += "your loan is at " + month + " Month and you will have to pay " + (rest * lo_money.get(5)) +  " but for this month "+lo_money.get(5)+"\n                                           thanks";
                    JOptionPane.showMessageDialog(null, msg);   
                }
            } else if (month <= 84) {
                msg += "you have paied " + flag + " Months\n";
                if (month == flag) {
                    msg += "your loan is at " + month + " Month and you have paied this month  \n                            thanks";
                    JOptionPane.showMessageDialog(null, msg);
                } else {
                    int rest = month - flag;
                    msg += "your loan is at " + month + " Month and you will have to pay " + (rest * lo_money.get(6)) +  " but for this month "+lo_money.get(6)+"\n                                             thanks";
                    JOptionPane.showMessageDialog(null, msg);
                }
            }
            msg = "";
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "no data selected");
        } finally{
            connect.closeConnection();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        clear();
        txt_nid.setEditable(true);
        txt_years.setEditable(true);
        txt_name.setEditable(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    public String getTxt_years() {
        return txt_years.getText();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
                UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txt_money;
    public static javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nid;
    public static javax.swing.JTextField txt_years;
    private javax.swing.JCheckBox yes;
    // End of variables declaration//GEN-END:variables
}
