/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.client;
import Controller.new_client;
import Controller.teller;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
import Model.connect;

/**
 *
 * @author omar
 */
public class TellerFrame extends javax.swing.JFrame {

    connect c = new connect();
    LoginFrame logIn = new LoginFrame();
    boolean flag;

    static String static_nationalid;

    public TellerFrame() {
        initComponents();
        setLocationRelativeTo(null);
        note.setVisible(false);
        update_table();
    }

    private void update_table() {
        try {
            ResultSet result = connect.startConnectionStatement().executeQuery("select * from client");
            client_table.setModel(DbUtils.resultSetToTableModel(result));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            connect.closeConnection();
        }
    }

    private void update_table2(JTable table) {
        try {
            ResultSet result;
            if (table == transfer_table) {
                result = connect.startConnectionStatement().executeQuery("select * from client where c_national_id='" + static_nationalid + "' or c_national_id='" + reciver_national_id.getText() + "'");
            } else {
                result = connect.startConnectionStatement().executeQuery("select * from client where c_national_id='" + static_nationalid + "'");
            }

            table.setModel(DbUtils.resultSetToTableModel(result));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            connect.closeConnection();
        }
    }

    private void clear() {
        nationalId.setText("");
        pass.setText("");
        name.setText("");
        address.setText("");
        age.setText("");
        phone.setText("");
        money.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        depositBtn = new javax.swing.JButton();
        withdrawBtn = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        cardPanel = new javax.swing.JPanel();
        newclient = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nationalId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        money = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        note = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        client_table = new javax.swing.JTable();
        oldClient = new javax.swing.JPanel();
        deposit = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        deposit_money = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        depoist_table = new javax.swing.JTable();
        doDepositBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        withdraw_table = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        withdraw_money = new javax.swing.JTextField();
        dowithdrawBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        reciver_national_id = new javax.swing.JTextField();
        transfer_money = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        transfer_table = new javax.swing.JTable();
        LoginIn = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nationalIDInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 350));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        depositBtn.setBackground(new java.awt.Color(102, 102, 255));
        depositBtn.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        depositBtn.setForeground(new java.awt.Color(255, 255, 255));
        depositBtn.setText("old client");
        depositBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositBtnActionPerformed(evt);
            }
        });

        withdrawBtn.setBackground(new java.awt.Color(102, 102, 255));
        withdrawBtn.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        withdrawBtn.setForeground(new java.awt.Color(255, 255, 255));
        withdrawBtn.setText("new client");
        withdrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBtnActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(102, 102, 255));
        Back.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(depositBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(withdrawBtn)
                .addGap(128, 128, 128)
                .addComponent(Back)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(withdrawBtn)
                    .addComponent(Back))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        cardPanel.setLayout(new java.awt.CardLayout());

        newclient.setBackground(new java.awt.Color(204, 204, 255));
        newclient.setForeground(new java.awt.Color(0, 102, 102));
        newclient.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("national id");

        nationalId.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        nationalId.setForeground(new java.awt.Color(0, 102, 102));
        nationalId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nationalIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nationalIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nationalIdKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("password");

        jLabel3.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("name");

        jLabel4.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("address");

        jLabel5.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("age");

        jLabel6.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("phone");

        jLabel7.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("money");

        name.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(0, 102, 102));
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });

        address.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        address.setForeground(new java.awt.Color(0, 102, 102));
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressKeyTyped(evt);
            }
        });

        age.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        age.setForeground(new java.awt.Color(0, 102, 102));
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });

        phone.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(0, 102, 102));
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneKeyTyped(evt);
            }
        });

        money.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        money.setForeground(new java.awt.Color(0, 102, 102));
        money.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                moneyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                moneyKeyTyped(evt);
            }
        });

        pass.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 102, 102));
        pass.setToolTipText("");
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("Register new Account");

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Cooper Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        note.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        note.setForeground(new java.awt.Color(255, 0, 0));
        note.setText("you must entre balance more than 500$");

        client_table.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        client_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(client_table);

        javax.swing.GroupLayout newclientLayout = new javax.swing.GroupLayout(newclient);
        newclient.setLayout(newclientLayout);
        newclientLayout.setHorizontalGroup(
            newclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newclientLayout.createSequentialGroup()
                .addGroup(newclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newclientLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel8))
                    .addGroup(newclientLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(315, 329, Short.MAX_VALUE))
            .addGroup(newclientLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(newclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(note)
                    .addGroup(newclientLayout.createSequentialGroup()
                        .addGroup(newclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(20, 20, 20)
                        .addGroup(newclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(newclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(money, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(age, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nationalId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane4)
                        .addContainerGap())))
        );
        newclientLayout.setVerticalGroup(
            newclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newclientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(newclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newclientLayout.createSequentialGroup()
                        .addGroup(newclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nationalId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(newclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(money, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(note, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        cardPanel.add(newclient, "card3");

        oldClient.setBackground(new java.awt.Color(204, 204, 255));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel12.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 0));
        jLabel12.setText("Money");

        deposit_money.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        deposit_money.setForeground(new java.awt.Color(102, 102, 255));
        deposit_money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deposit_moneyActionPerformed(evt);
            }
        });
        deposit_money.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                deposit_moneyKeyTyped(evt);
            }
        });

        depoist_table.setFont(new java.awt.Font("Cooper Black", 0, 10)); // NOI18N
        depoist_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(depoist_table);

        doDepositBtn.setBackground(new java.awt.Color(102, 102, 255));
        doDepositBtn.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        doDepositBtn.setForeground(new java.awt.Color(255, 255, 255));
        doDepositBtn.setText("Deposit");
        doDepositBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doDepositBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deposit_money, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(doDepositBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deposit_money, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addComponent(doDepositBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        deposit.addTab("Deposit", jPanel4);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        withdraw_table.setFont(new java.awt.Font("Cooper Black", 0, 10)); // NOI18N
        withdraw_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(withdraw_table);

        jLabel13.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 0));
        jLabel13.setText("Money");

        withdraw_money.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        withdraw_money.setForeground(new java.awt.Color(102, 102, 255));
        withdraw_money.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                withdraw_moneyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                withdraw_moneyKeyTyped(evt);
            }
        });

        dowithdrawBtn.setBackground(new java.awt.Color(102, 102, 255));
        dowithdrawBtn.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        dowithdrawBtn.setForeground(new java.awt.Color(255, 255, 255));
        dowithdrawBtn.setText("Withdraw");
        dowithdrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dowithdrawBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(withdraw_money, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(dowithdrawBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(withdraw_money, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(dowithdrawBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        deposit.addTab("Withdraw", jPanel3);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel14.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 0));
        jLabel14.setText("Reciver National id");

        jLabel15.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 0));
        jLabel15.setText("Money");

        reciver_national_id.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        reciver_national_id.setForeground(new java.awt.Color(102, 102, 255));
        reciver_national_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reciver_national_idActionPerformed(evt);
            }
        });
        reciver_national_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reciver_national_idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                reciver_national_idKeyTyped(evt);
            }
        });

        transfer_money.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        transfer_money.setForeground(new java.awt.Color(102, 102, 255));
        transfer_money.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                transfer_moneyKeyTyped(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Transfer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton3KeyTyped(evt);
            }
        });

        transfer_table.setFont(new java.awt.Font("Cooper Black", 0, 10)); // NOI18N
        transfer_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(transfer_table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reciver_national_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transfer_money, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(reciver_national_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(transfer_money, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        deposit.addTab("Transfer Money", jPanel2);

        javax.swing.GroupLayout oldClientLayout = new javax.swing.GroupLayout(oldClient);
        oldClient.setLayout(oldClientLayout);
        oldClientLayout.setHorizontalGroup(
            oldClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deposit)
        );
        oldClientLayout.setVerticalGroup(
            oldClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deposit)
        );

        cardPanel.add(oldClient, "card4");

        LoginIn.setBackground(new java.awt.Color(204, 204, 255));

        jLabel10.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 0));
        jLabel10.setText("Nationl id");

        jLabel11.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 0));
        jLabel11.setText("Password");

        nationalIDInput.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        nationalIDInput.setForeground(new java.awt.Color(102, 102, 255));
        nationalIDInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalIDInputActionPerformed(evt);
            }
        });

        passwordInput.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        passwordInput.setForeground(new java.awt.Color(102, 102, 255));

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginInLayout = new javax.swing.GroupLayout(LoginIn);
        LoginIn.setLayout(LoginInLayout);
        LoginInLayout.setHorizontalGroup(
            LoginInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginInLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(LoginInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nationalIDInput, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(passwordInput, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        LoginInLayout.setVerticalGroup(
            LoginInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginInLayout.createSequentialGroup()
                .addGroup(LoginInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginInLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(LoginInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginInLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(LoginInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(LoginInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nationalIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(LoginInLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        cardPanel.add(LoginIn, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositBtnActionPerformed
        cardPanel.removeAll();
        cardPanel.add(LoginIn);
        cardPanel.repaint();
        cardPanel.revalidate();
    }//GEN-LAST:event_depositBtnActionPerformed

    private void withdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawBtnActionPerformed
        cardPanel.removeAll();
        cardPanel.add(newclient);
        cardPanel.repaint();
        cardPanel.revalidate();
    }//GEN-LAST:event_withdrawBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String a = nationalIDInput.getText();
        String p = passwordInput.getText();
        if (a.equals("") || p.equals("")) {
            JOptionPane.showMessageDialog(null, "Please Comlete Data");
        } else {
            try {
                ResultSet result = connect.startConnectionStatement().executeQuery("select * from client where c_national_id='" + nationalIDInput.getText() + "'");
                a = "";
                p = "";
                while (result.next()) {
                    a = result.getString(1);
                    p = result.getString(6);
                }
                if (a.equals(nationalIDInput.getText()) && p.equals(passwordInput.getText())) {
                    static_nationalid = nationalIDInput.getText();
                    cardPanel.removeAll();
                    cardPanel.add(oldClient);
                    cardPanel.repaint();
                    cardPanel.revalidate();
                    nationalIDInput.setText("");
                    passwordInput.setText("");
                    update_table2(depoist_table);
                    update_table2(withdraw_table);
                    update_table2(transfer_table);
                } else {
                    JOptionPane.showMessageDialog(null, "you entered wrong name or password");
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            } finally {
                connect.closeConnection();
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void nationalIDInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalIDInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalIDInputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (nationalId.getText().equals("") && pass.getText().equals("") && name.getText().equals("")
                && address.getText().equals("") && age.getText().equals("") && phone.getText().equals("")
                && money.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please, Fill All Fields");
        } else if (nationalId.getText().equals("") || pass.getText().equals("") || name.getText().equals("")
                || address.getText().equals("") || age.getText().equals("") || phone.getText().equals("")
                || money.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Complete All Data");
        } else if (Double.parseDouble(money.getText()) < 500) {
            JOptionPane.showMessageDialog(null, "You Must Deposit 500 LE Or More");
        } else if (nationalId.getText().length() < 14) {
            JOptionPane.showMessageDialog(null, "National ID Must Be 14 Digit");
        } else if (pass.getText().length() < 8) {
            JOptionPane.showMessageDialog(null, "Password Must Be 8 Digit Or More");
        } else if (phone.getText().length() < 11) {
            JOptionPane.showMessageDialog(null, "Phone Number Must Be 11 Digit");
        } else if (Integer.parseInt(age.getText()) < 21 || Integer.parseInt(age.getText()) > 120) {
            JOptionPane.showMessageDialog(null, "Your Age Must Between 21 and 120 Year");
        } else {
            new_client nnew = new new_client(nationalId.getText(), name.getText(), address.getText(), phone.getText(), Integer.parseInt(age.getText()));
            nnew.setMoney(Double.parseDouble(money.getText()));
            nnew.setPassword(pass.getText());

            teller t1 = new teller();
            t1.openNewaccount(nnew);
            if (teller.new_flag) {
                note.setVisible(false);
                update_table();
                clear();
            }
            else
                JOptionPane.showMessageDialog(null, "NO ROW CREATED");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void doDepositBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doDepositBtnActionPerformed
        if (deposit_money.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "enter money");
        } else {
            client cc = new client(static_nationalid);
            double m = Double.parseDouble(deposit_money.getText());
            cc.setMoney(m);
            teller tt = new teller();
            tt.deposit(cc);
            if (teller.deposite_flag) {
                update_table2(depoist_table);
                update_table2(withdraw_table);
                update_table2(transfer_table);
                update_table();
                deposit_money.setText("");
            }
        }
    }//GEN-LAST:event_doDepositBtnActionPerformed

    private void deposit_moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deposit_moneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deposit_moneyActionPerformed

    private void passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyReleased
        String password = pass.getText();
        if (password.length() < 8) {
            pass.setBackground(Color.red);
        } else {
            pass.setBackground(Color.white);
        }
    }//GEN-LAST:event_passKeyReleased

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_nameKeyTyped

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void addressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyTyped

    }//GEN-LAST:event_addressKeyTyped

    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        } else if (age.getText().length() > 2) {
            evt.consume();
        }
    }//GEN-LAST:event_ageKeyTyped

    private void phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        } else if (phone.getText().length() >= 11) {
            evt.consume();
        }
    }//GEN-LAST:event_phoneKeyTyped

    private void moneyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moneyKeyTyped
        note.setVisible(true);
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_moneyKeyTyped

    private void nationalIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nationalIdKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        } else if (nationalId.getText().length() >= 14) {
            evt.consume();
        }
    }//GEN-LAST:event_nationalIdKeyTyped

    private void nationalIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nationalIdKeyReleased
        String id = nationalId.getText();
        if (id.length() < 14) {
            nationalId.setBackground(Color.red);
        } else {
            nationalId.setBackground(Color.white);
        }
    }//GEN-LAST:event_nationalIdKeyReleased

    private void nationalIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nationalIdKeyPressed

    }//GEN-LAST:event_nationalIdKeyPressed

    private void deposit_moneyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deposit_moneyKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_deposit_moneyKeyTyped

    private void transfer_moneyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_transfer_moneyKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_transfer_moneyKeyTyped

    private void reciver_national_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reciver_national_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reciver_national_idActionPerformed

    private void withdraw_moneyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_withdraw_moneyKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_withdraw_moneyKeyTyped

    private void reciver_national_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reciver_national_idKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        } else if (reciver_national_id.getText().length() >= 14) {
            evt.consume();
        }
    }//GEN-LAST:event_reciver_national_idKeyTyped

    private void reciver_national_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reciver_national_idKeyReleased
        String id = reciver_national_id.getText();
        if (id.length() < 14) {
            reciver_national_id.setBackground(Color.red);
        } else {
            reciver_national_id.setBackground(Color.white);
            flag = true;
            update_table2(transfer_table);
        }
    }//GEN-LAST:event_reciver_national_idKeyReleased

    private void dowithdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dowithdrawBtnActionPerformed
        if (withdraw_money.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "enter money");
        } else {
            client c = new client(static_nationalid);
            double m = Double.parseDouble(withdraw_money.getText());
            c.setMoney(m);
            teller tt = new teller();
            tt.withdraw(c);
            if (teller.withdraw_flag) {
                update_table2(depoist_table);
                update_table2(withdraw_table);
                update_table2(transfer_table);
                update_table();
                withdraw_money.setText("");
            }
        }
    }//GEN-LAST:event_dowithdrawBtnActionPerformed

    private void withdraw_moneyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_withdraw_moneyKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_withdraw_moneyKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (flag && !transfer_money.getText().equals("")) {
            client c1 = new client(static_nationalid);
            client c2 = new client(reciver_national_id.getText());
            Double c1money = Double.parseDouble(transfer_money.getText());
            c1.setMoney(c1money);
            teller t2 = new teller();
            t2.transfer_money(c1, c2);
            update_table2(depoist_table);
            update_table2(withdraw_table);
            update_table2(transfer_table);
            update_table();
            transfer_money.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "no selected data");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3KeyTyped

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        setVisible(false);
        logIn.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void moneyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moneyKeyReleased

    }//GEN-LAST:event_moneyKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TellerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TellerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TellerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TellerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TellerFrame log = new TellerFrame();
                log.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JPanel LoginIn;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JTable client_table;
    private javax.swing.JTable depoist_table;
    private javax.swing.JTabbedPane deposit;
    private javax.swing.JButton depositBtn;
    private javax.swing.JTextField deposit_money;
    private javax.swing.JButton doDepositBtn;
    private javax.swing.JButton dowithdrawBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField money;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nationalIDInput;
    private javax.swing.JTextField nationalId;
    private javax.swing.JPanel newclient;
    private javax.swing.JLabel note;
    private javax.swing.JPanel oldClient;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField reciver_national_id;
    private javax.swing.JTextField transfer_money;
    private javax.swing.JTable transfer_table;
    private javax.swing.JButton withdrawBtn;
    private javax.swing.JTextField withdraw_money;
    private javax.swing.JTable withdraw_table;
    // End of variables declaration//GEN-END:variables
}
